# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradefood', '0002_remove_offer_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='sms_notifs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='sms_notifs',
            field=models.BooleanField(default=False),
        ),
    ]
