# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 20:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tradefood', '0002_auto_20171115_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 15, 20, 34, 54, 429815, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 15, 20, 34, 54, 428273, tzinfo=utc)),
        ),
    ]
