# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tradefood', '0003_auto_20171115_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offer',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
