# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradefood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='category',
            field=models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('OTHER', 'Other')], default='RESTAURANT', max_length=30),
        ),
    ]
