# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradefood', '0002_auto_20171114_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
