# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradefood', '0004_auto_20171115_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='duration',
            field=models.FloatField(choices=[(0.5, '30 minutes'), (1.0, '1 hour'), (2.0, '2 hours'), (3.0, '3 hours')], default=1.0),
        ),
    ]
