# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradefood', '0006_auto_20171115_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tradefood.Merchant'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tradefood.Offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='tradefood.Merchant'),
        ),
    ]
