# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradefood', '0007_auto_20171116_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
