# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradefood', '0008_offer_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='bid_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
