# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradefood', '0010_auto_20171117_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='retail_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='retail_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
    ]
