# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradefood', '0011_auto_20171117_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='duration',
        ),
    ]
