# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradefood', '0012_auto_20171118_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date_posted',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='date_posted',
            field=models.DateTimeField(),
        ),
    ]
